# Use this kustomization after istio control-plane installation
namespace: istio-system
resources:
# Istio IngressClass
- istio-ingressclass.yml
# Addons
- https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/prometheus.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/kiali.yaml
- https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/jaeger.yaml
# Ingresses for addons
- kiali-ing.yml
- jaeger-ing.yml
